version: '3'
services:
  go-url-shortening-service:
    restart: always
    image: go-url-shortening-service
    ports:
      - 8000:8000
    depends_on:
      - app_redis
  app_redis:
    restart: always
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - /tmp/redis-data:/tmp